### ISSUE TITLE
Botón oscuro al estar seleccionado (Trivial)

### ISSUE THREAD

**Issue by Sopapadehojaldre** [DiegoFioretti/Project-Plasaleos#3]
Rate: 100%

Descripción
Cuando presiono en los menús de acción que están en las esquinas inferiores de la pantalla durante la partida, al desplegarse las opciones, el botón que abrió el menú queda oscurecido de la misma manera que la opción que no está habilitada, me está indicando que el botón no está habilitado para usarlo cuando sí puedo utilizarlo para cerrar el menú.

Resultado obtenido
El botón del menú de acción queda oscuro como si estuviera deshabilitado pero me permite utilizarlo.

Resultado esperado
Que no me permita usar el botón porque está deshabilitado, o bien que el botón esté iluminado.

Captura
https://drive.google.com/file/d/1voTtdvXQfiEczbktgdaXB73xgvAC20QP/view?usp=drivesdk

**Comment by Marchin** [comment]
Hola! En un rato nos ponemos a resolver el issue, mientras te pido que me pases tu nombre y links que quieras dejar de contacto y portfolio para los créditos en la descripción del repositorio. Sé que este no es el mejor medio pero no encontré otra forma de contactarte pido disculpas.

Podes mandarme lo información a mmonterrosa94@gmail.com

Saludos

**Comment by Marchin** [comment]
No es que se puede presionar el botón en sí sino que presionando en la pantalla ya se salé del menú. De todas maneras hicimos que desaparezca el botón de la esquina opuesta para que sea más claro.
