### ISSUE TITLE
Botón para cerrar ventana incómodo (Nice to have)

### ISSUE THREAD

**Issue by Sopapadehojaldre** [DiegoFioretti/Project-Plasaleos#7]
Descripción
Las ventanas de tutoriales tienen el botón para cerrarlas arriba a la izquierda.
 Me es poco intuitivo ya que normalmente el botón está arriba a la derecha, y en algunos casos abajo a la derecha, también hay juegos donde no le ponen botón sino que solo tocando una vez el cartel, éste se cierra.

Captura
https://drive.google.com/file/d/1l4qEJDzTH30Okabts-aKr_BjoauoGZ56/view?usp=drivesdk

**Comment by Marchin** [comment]
Se optó que el tocar el cartel cierre el tutorial
