### ISSUE TITLE
Testear Animales e interacción de liana y la gravedad.

### ISSUE THREAD

**Issue by Marchin** [DiegoFioretti/Project-Plasaleos#9]
Hicimos un nivel de testeo que se encuentra en la esquina superior derecha de la primera pantalla. Testear y dar feedback de las siguientes cosas:

Animal:
Los animales deben moverse normalmente, cuando ven a un alien FRENTE suyo empezar a perseguirlos, cuando lo alcanza debe comerlos, esto le toma unas segundos, y se repite. Hay un bug visual ya sabido en el que los aliens no quedan en la boca del animal mientras son deborados sino en la cola.

Gravedad-Liana:
La gravedad funciona en 8 direcciones. Cuando la gravedad se encuentra tranversal al piso donde caminan los aliens estos se mueven a velocidad normal. Cuando se encuentra en uno de las direcciones adyacentes a la transversal del piso van más rápido o lento segundo en qué dirección estén mirando las entidades. Esto funciona perfectamente en el piso pero cuando se pone una liana en angulos no multiplos de 45° puede generar comportamiento indeseado, por favor testear los distintos casos y dar detalles al respecto.

Mecánica del susto:
Implementamos también el susto haciendo que en un radio determinado las entedidades se alejen de ese punto. Testear el correcto funcionamiento.

Por faver probar todo esto en la build "Pre-Final" y revisar que los bugs reportados estén corregidos

**Comment by Marchin** [comment]
Se actualizó la build corrigiendo un error con los botones de ambiente apareciendo antes de lo debido, y un sistema de guardado implementado.

**Comment by Sopapadehojaldre** [comment]
Acabo de revisar rápido esta última build, están seguros que es la que corresponde? Porque está rota por todos lados, les pasó una lista de lo que encontré por acá para que revisen:
01. No está nivel nuevo de testeo.
02. Menú de opciones en el mapa, tiene todos los botones encimados.
03. Cartel de Victory no rota.
04. Nivel 6 y 7 no tienen botones de acción ni pausa, no puedo pasar el nivel ni salir del nivel.
05. Nivel 5 y 51 en el cartel de Game Over pone Next level.
06. La opción Next level no aparece en los siguientes niveles: 1, 3, 4, 8, 52.
07. Al salir del juego y volver a entrar, se pierde el progreso.

Si consideran necesario hago los reportes, pero me parece que en el estado en el que está, no vale la pena.

**Comment by Marchin** [comment]
Hola, efectivamente tuvimos un par de problemas, vamos a intentar tener el apk reparado dentro de la próxima hora o 2, perdón por el inconveniente

**Comment by Marchin** [comment]
Ahí actualizamos la build. El nivel de prueba no tiene cartel de game over. En cuanto al botón de Next Level funciona hasta los niveles donde hay o hubo un candado delante, sabemos que no es lo mejor y estamos trabajando para mejorarlo
